apiVersion: v1
kind: ConfigMap
metadata:
  name: emqx-config
  namespace: default
data:
  EMQX_NAME: emqx
  EMQX_CLUSTER__DISCOVERY: dns
  EMQX_CLUSTER__DNS__TYPE: srv
  EMQX_CLUSTER__DNS__NAME: emqx-headless.default.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: emqx-headless
  namespace: default
spec:
  clusterIP: None
  selector:
    app: emqx
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: dashboard
      port: 18083
      targetPort: 18083
    - name: mgmt
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emqx
  namespace: default
spec:
  serviceName: emqx-headless
  replicas: 3
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
        - name: emqx
          image: emqx/emqx:5.0.25
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 18083
              name: dashboard
            - containerPort: 8081
              name: mgmt
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: EMQX_NODE__NAME
              value: emqx@$(POD_NAME).emqx-headless.default.svc.cluster.local
          envFrom:
            - configMapRef:
                name: emqx-config
          volumeMounts:
            - name: emqx-data
              mountPath: /opt/emqx/data
  volumeClaimTemplates:
    - metadata:
        name: emqx-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
