apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-info-nginx-v1-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: student-info-nginx
      version: "1.0"
  template:
    metadata:
      labels:
        app: student-info-nginx
        version: "1.0"
    spec:
      containers:
        - name: student-info-nginx-container
          image: ivkeex/student-info-nginx:1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: student-info-nginx-v1-service
spec:
  selector:
    app: student-info-nginx
    version: "1.0"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
